import { describe, it, expect } from 'vitest';
import { renderCodexAgentsMd } from '../../../src/renderers/codex/agents-md.js';
import type { CoreTeam } from '../../../src/core/types.js';

function makeTeam(overrides: Partial<CoreTeam> = {}): CoreTeam {
  return {
    version: '2',
    project: { name: 'test-project' },
    agents: {},
    ...overrides,
  };
}

describe('renderCodexAgentsMd', () => {
  it('renders project name and description', () => {
    const team = makeTeam({
      project: { name: 'My App', description: 'A cool app' },
      agents: {
        dev: {
          id: 'dev',
          description: 'Developer',
          runtime: { tools: ['write_file'] },
          instructions: [],
        },
      },
    });
    const file = renderCodexAgentsMd(team);
    expect(file.path).toBe('AGENTS.md');
    expect(file.content).toContain('# My App');
    expect(file.content).toContain('A cool app');
  });

  it('renders agent roster table', () => {
    const team = makeTeam({
      agents: {
        orchestrator: {
          id: 'orchestrator',
          description: 'Coordinates work',
          runtime: { tools: ['execute_command'] },
          instructions: [],
          metadata: { handoffs: ['dev', 'reviewer'] },
        },
        dev: {
          id: 'dev',
          description: 'Implements features',
          runtime: { tools: ['write_file', 'execute_command'] },
          instructions: [],
        },
        reviewer: {
          id: 'reviewer',
          description: 'Reviews code',
          runtime: { tools: ['read_file'] },
          instructions: [],
        },
      },
    });
    const file = renderCodexAgentsMd(team);
    expect(file.content).toContain('| **orchestrator** | Coordinates work | workspace-write | dev, reviewer |');
    expect(file.content).toContain('| **dev** | Implements features | workspace-write |');
    expect(file.content).toContain('| **reviewer** | Reviews code | read-only |');
  });

  it('renders policies section', () => {
    const team = makeTeam({
      agents: {
        dev: {
          id: 'dev',
          description: 'Dev',
          runtime: {},
          instructions: [],
        },
      },
      policies: {
        sandbox: { enabled: true },
        permissions: {
          rules: {
            deny: ['Bash(rm -rf *)'],
            allow: ['Bash(git status)'],
          },
        },
      },
    });
    const file = renderCodexAgentsMd(team);
    expect(file.content).toContain('Sandbox: **enabled**');
    expect(file.content).toContain('`Bash(rm -rf *)`');
    expect(file.content).toContain('`Bash(git status)`');
  });

  it('renders network restrictions', () => {
    const team = makeTeam({
      agents: {
        dev: { id: 'dev', description: 'Dev', runtime: {}, instructions: [] },
      },
      policies: {
        network: { allowedDomains: ['api.example.com', 'cdn.example.com'] },
      },
    });
    const file = renderCodexAgentsMd(team);
    expect(file.content).toContain('api.example.com, cdn.example.com');
  });

  it('includes TeamCast footer', () => {
    const team = makeTeam({
      agents: {
        dev: { id: 'dev', description: 'Dev', runtime: {}, instructions: [] },
      },
    });
    const file = renderCodexAgentsMd(team);
    expect(file.content).toContain('Generated by [TeamCast]');
  });
});
