// Generates AGENTS.md for Codex target.
// AGENTS.md is a top-level team instructions file that Codex uses alongside
// per-agent .toml configs and SKILL.md files.

import type { CoreAgent, CoreTeam } from '../../core/types.js';
import type { RenderedFile } from '../types.js';
import { renderInstructionBlocks } from '../../core/instructions.js';

function deriveSandboxLabel(agent: CoreAgent): string {
  const hasWrite = agent.runtime.tools?.includes('write_file') ?? false;
  const hasExec = agent.runtime.tools?.includes('execute_command') ?? false;
  return hasWrite || hasExec ? 'workspace-write' : 'read-only';
}

export function renderCodexAgentsMd(team: CoreTeam): RenderedFile {
  const lines: string[] = [];

  lines.push(`# ${team.project.name}`);
  lines.push('');

  if (team.project.description) {
    lines.push(team.project.description);
    lines.push('');
  }

  lines.push('## Team Overview');
  lines.push('');
  lines.push('This project uses a multi-agent architecture managed by TeamCast.');
  lines.push('Agent configuration: `teamcast.yaml` (run `teamcast generate` to regenerate).');
  lines.push('');

  // Agent roster table
  lines.push('## Agents');
  lines.push('');
  lines.push('| Agent | Role | Sandbox | Delegates to |');
  lines.push('|-------|------|---------|--------------|');

  for (const [agentId, agent] of Object.entries(team.agents)) {
    const sandbox = deriveSandboxLabel(agent);
    const handoffs = agent.metadata?.handoffs?.join(', ') || '—';
    lines.push(`| **${agentId}** | ${agent.description} | ${sandbox} | ${handoffs} |`);
  }
  lines.push('');

  // Shared instructions from instruction fragments (common across agents)
  const sharedBlocks = collectSharedInstructions(team);
  if (sharedBlocks.length > 0) {
    lines.push('## Shared Instructions');
    lines.push('');
    lines.push(sharedBlocks.join('\n\n'));
    lines.push('');
  }

  // Environment / policies
  if (team.policies) {
    lines.push('## Policies');
    lines.push('');

    if (team.policies.sandbox?.enabled) {
      lines.push('- Sandbox: **enabled**');
    }

    const deny = team.policies.permissions?.rules?.deny ?? [];
    if (deny.length > 0) {
      lines.push(`- Denied: ${deny.map((d) => `\`${d}\``).join(', ')}`);
    }

    const allow = team.policies.permissions?.rules?.allow ?? [];
    if (allow.length > 0) {
      lines.push(`- Allowed: ${allow.map((a) => `\`${a}\``).join(', ')}`);
    }

    if (team.policies.network?.allowedDomains?.length) {
      lines.push(`- Network: restricted to ${team.policies.network.allowedDomains.join(', ')}`);
    }

    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [TeamCast](https://github.com/Katoshy/teamcast)*');
  lines.push('');

  return {
    path: 'AGENTS.md',
    content: lines.join('\n'),
  };
}

/**
 * Collect instruction blocks that appear in more than one agent.
 * These are "shared" instructions worth surfacing at the team level.
 */
function collectSharedInstructions(team: CoreTeam): string[] {
  const blockCounts = new Map<string, number>();
  const blockContent = new Map<string, string>();

  for (const agent of Object.values(team.agents)) {
    const rendered = renderInstructionBlocks(agent.instructions);
    if (rendered) {
      const key = rendered.trim();
      blockCounts.set(key, (blockCounts.get(key) ?? 0) + 1);
      blockContent.set(key, rendered);
    }
  }

  const shared: string[] = [];
  for (const [key, count] of blockCounts) {
    if (count > 1) {
      shared.push(blockContent.get(key)!);
    }
  }

  return shared;
}
