import { renderInstructionBlocks } from '../../core/instructions.js';
import type { CoreAgent } from '../../core/types.js';
import type { PlatformRenderer, RenderedFile, TeamRenderSpec } from '../types.js';
import type { TargetContext } from '../target-context.js';
import { CODEX_SKILL_MAP, reverseMapToolsToSkills } from './skill-map.js';
import { CODEX_TOOLS } from './tools.js';
import { renderCodexSkillMd } from './skill-md.js';
import { renderCodexAgentsMd } from './agents-md.js';

function escapeTomlString(value: string): string {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"');
}

function escapeTomlMultiline(value: string): string {
  return value
    .replace(/\r\n/g, '\n')
    .replaceAll('"""', '\\"""');
}

function usesTool(agent: CoreAgent, tool: string): boolean {
  return agent.runtime.tools?.includes(tool) ?? false;
}

function buildDeveloperInstructions(agent: CoreAgent): string {
  const sections: string[] = [
    `You are ${agent.id}. ${agent.description}`,
  ];

  const renderedInstructions = renderInstructionBlocks(agent.instructions);
  if (renderedInstructions) {
    sections.push(renderedInstructions);
  }

  if (agent.metadata?.handoffs?.length) {
    sections.push(`## Delegation\n\nYou may delegate to: ${agent.metadata.handoffs.join(', ')}.`);
  }

  if (agent.runtime.tools?.length) {
    sections.push(`## Allowed Tool Intents\n\n${agent.runtime.tools.join(', ')}`);
  }

  if (agent.runtime.disallowedTools?.length) {
    sections.push(`## Restricted Tool Intents\n\nAvoid using: ${agent.runtime.disallowedTools.join(', ')}`);
  }

  if (agent.runtime.skillDocs?.length) {
    sections.push(`## Skill Docs\n\nFollow these local skills when relevant: ${agent.runtime.skillDocs.join(', ')}.`);
  }

  return sections.join('\n\n').trim();
}

function deriveSandboxMode(agent: CoreAgent): 'read-only' | 'workspace-write' {
  return usesTool(agent, 'write_file') || usesTool(agent, 'execute_command')
    ? 'workspace-write'
    : 'read-only';
}

function renderAgentConfig(agent: CoreAgent): string {
  const lines: string[] = [];

  if (agent.runtime.model) {
    lines.push(`model = "${escapeTomlString(agent.runtime.model)}"`);
  }
  if (agent.runtime.reasoningEffort) {
    lines.push(`model_reasoning_effort = "${agent.runtime.reasoningEffort}"`);
  }
  lines.push(`sandbox_mode = "${deriveSandboxMode(agent)}"`);
  lines.push(`developer_instructions = """\n${escapeTomlMultiline(buildDeveloperInstructions(agent))}\n"""`);

  if (!usesTool(agent, 'execute_command')) {
    lines.push('');
    lines.push('[features]');
    lines.push('shell_tool = false');
  }

  return `${lines.join('\n')}\n`;
}

export class CodexRenderer implements PlatformRenderer {
  render(spec: TeamRenderSpec): RenderedFile[] {
    const files: RenderedFile[] = [];
    const team = spec.team;

    const configLines: string[] = [
      `# Generated by TeamCast for ${team.project.name}`,
      '',
      '[features]',
      'multi_agent = true',
    ];

    for (const [agentId, agent] of Object.entries(team.agents)) {
      configLines.push('');
      configLines.push(`[agents.${agentId}]`);
      configLines.push(`description = "${escapeTomlString(agent.description)}"`);
      configLines.push(`config_file = "agents/${escapeTomlString(agentId)}.toml"`);

      files.push({
        path: `.codex/agents/${agentId}.toml`,
        content: renderAgentConfig(agent),
      });
    }

    files.push({
      path: `.codex/config.toml`,
      content: `${configLines.join('\n')}\n`,
    });

    files.push(...renderCodexSkillMd(team));
    files.push(renderCodexAgentsMd(team));

    return files;
  }
}

export function createCodexTarget(): TargetContext {
  return {
    name: 'codex',
    renderer: new CodexRenderer(),
    skillMap: CODEX_SKILL_MAP,
    knownTools: CODEX_TOOLS,
    reverseMapTools: reverseMapToolsToSkills,
  };
}
