import type { AgentForgeManifest } from '../../types/manifest.js';
import { hasAllowList } from '../../types/manifest.js';
import type { GeneratedFile } from '../types.js';

// Generates AGENTS.md — universal AI agent documentation.
// Read by Codex, GitHub Copilot, Cursor, and other AI coding tools.
// Content is tool-agnostic: project structure, conventions, how to contribute.
export function renderAgentsMd(manifest: AgentForgeManifest): GeneratedFile {
  const lines: string[] = [];
  const { project, agents, policies } = manifest;

  lines.push(`# ${project.name}`);
  lines.push('');

  if (project.description) {
    lines.push(project.description);
    lines.push('');
  }

  // Project structure hint — generic, helps any AI understand the codebase layout
  lines.push('## Project Overview');
  lines.push('');
  lines.push('This project uses a multi-agent architecture managed by AgentForge.');
  lines.push(`Agent configuration: \`agentforge.yaml\` (edit this file, then run \`agentforge generate\`)`);
  lines.push('');

  // Agent roster — who is in the team and what they do
  lines.push('## Agent Roster');
  lines.push('');

  for (const [agentId, agent] of Object.entries(agents)) {
    const model = agent.model ?? manifest.settings?.default_model ?? 'sonnet';
    lines.push(`### ${agentId}`);
    lines.push('');
    lines.push(`**Role:** ${agent.description}`);
    lines.push(`**Model:** ${model}`);
    lines.push('');

    if (agent.tools) {
      if (hasAllowList(agent.tools)) {
        lines.push(`**Allowed tools:** ${agent.tools.allow.join(', ')}`);
        if (agent.tools.deny?.length) {
          lines.push(`**Restricted tools:** ${agent.tools.deny.join(', ')}`);
        }
      } else {
        lines.push(`**Restricted tools:** ${agent.tools.deny.join(', ')}`);
      }
    }

    if (agent.handoffs?.length) {
      lines.push(`**Can delegate to:** ${agent.handoffs.join(', ')}`);
    }

    if (agent.skills?.length) {
      lines.push(`**Skills:** ${agent.skills.join(', ')}`);
    }

    lines.push('');
  }

  // Access control summary — useful for any agent to know what's safe to do
  lines.push('## Access Control');
  lines.push('');

  if (policies?.permissions?.allow?.length) {
    lines.push('**Permitted operations:**');
    for (const rule of policies.permissions.allow) {
      lines.push(`- \`${rule}\``);
    }
    lines.push('');
  }

  if (policies?.permissions?.deny?.length) {
    lines.push('**Prohibited operations:**');
    for (const rule of policies.permissions.deny) {
      lines.push(`- \`${rule}\``);
    }
    lines.push('');
  }

  if (policies?.permissions?.ask?.length) {
    lines.push('**Requires confirmation:**');
    for (const rule of policies.permissions.ask) {
      lines.push(`- \`${rule}\``);
    }
    lines.push('');
  }

  if (policies?.network?.allowed_domains?.length) {
    lines.push(`**Network access:** restricted to ${policies.network.allowed_domains.join(', ')}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [AgentForge](https://github.com/agentforge/agentforge)*');
  lines.push('');

  return {
    path: 'AGENTS.md',
    content: lines.join('\n'),
  };
}
