import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, mkdtempSync, writeFileSync, rmSync, existsSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { importFromClaudeDir } from '../../../src/importer/claude.js';
import { importFromCodexDir } from '../../../src/importer/codex.js';

let TMP: string;

function setupClaudeDir(files: Record<string, string>) {
  mkdirSync(join(TMP, '.claude', 'agents'), { recursive: true });
  for (const [name, content] of Object.entries(files)) {
    writeFileSync(join(TMP, '.claude', 'agents', name), content, 'utf-8');
  }
}

function setupSettings(settings: object) {
  mkdirSync(join(TMP, '.claude'), { recursive: true });
  writeFileSync(
    join(TMP, '.claude', 'settings.json'),
    JSON.stringify(settings, null, 2),
    'utf-8',
  );
}

function setupCodexDir(configEntries: Array<{ name: string; description: string; content: string }>) {
  mkdirSync(join(TMP, '.codex', 'agents'), { recursive: true });
  writeFileSync(
    join(TMP, '.codex', 'config.toml'),
    [
      '# Generated by TeamCast',
      '',
      '[features]',
      'multi_agent = true',
      '',
      ...configEntries.flatMap((entry) => [
        `[agents.${entry.name}]`,
        `description = "${entry.description}"`,
        `config_file = "agents/${entry.name}.toml"`,
        '',
      ]),
    ].join('\n'),
    'utf-8',
  );

  for (const entry of configEntries) {
    writeFileSync(join(TMP, '.codex', 'agents', `${entry.name}.toml`), entry.content, 'utf-8');
  }
}

describe('importFromClaudeDir', () => {
  beforeEach(() => {
    TMP = mkdtempSync(join(tmpdir(), 'teamcast-import-'));
  });

  afterEach(() => {
    if (existsSync(TMP)) rmSync(TMP, { recursive: true });
  });

  it('imports agent from .md frontmatter', () => {
    setupClaudeDir({
      'developer.md': [
        '---',
        'name: developer',
        'description: Implements features and fixes bugs',
        'model: claude-sonnet-4-6',
        'tools: [Read, Write, Edit, Bash, Grep, Glob]',
        '---',
        '',
        'Custom behavior instructions here.',
      ].join('\n'),
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    const agent = result.team.claude?.agents.developer as any;

    expect(agent).toBeDefined();
    expect(agent.description).toBe('Implements features and fixes bugs');
    expect(agent.model).toBe('sonnet');
    // Read+Grep+Glob -> read_files, Bash -> execute; Write and Edit remain (no MultiEdit to complete write_files)
    expect(agent?.tools).toEqual(['read_files', 'execute', 'Write', 'Edit']);
    expect(agent?.instruction_blocks).toEqual([{ kind: 'behavior', content: 'Custom behavior instructions here.' }]);
  });

  it('imports multiple agents', () => {
    setupClaudeDir({
      'planner.md': [
        '---',
        'name: planner',
        'description: Plans implementation',
        'model: claude-opus-4-6',
        'tools: [Read, Grep, Glob]',
        '---',
      ].join('\n'),
      'reviewer.md': [
        '---',
        'name: reviewer',
        'description: Reviews code',
        'model: claude-haiku-4-5-20251001',
        'tools: [Read, Grep, Glob]',
        '---',
      ].join('\n'),
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    expect(Object.keys(result.team.claude?.agents ?? {})).toHaveLength(2);
    expect((result.team.claude?.agents.planner as any).model).toBe('opus');
    expect((result.team.claude?.agents.reviewer as any).model).toBe('haiku');
  });

  it('imports permissions from settings.json', () => {
    setupClaudeDir({
      'dev.md': '---\nname: dev\ndescription: Dev\n---\n',
    });
    setupSettings({
      permissions: {
        allow: ['Bash(npm test)'],
        deny: ['Write(.env*)', 'Bash(rm -rf *)'],
      },
      sandbox: {
        enabled: true,
        autoAllowBashIfSandboxed: true,
      },
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    expect((result.team.claude as any)?.policies?.permissions?.rules?.allow).toEqual(['Bash(npm test)']);
    expect((result.team.claude as any)?.policies?.permissions?.rules?.deny).toContain('Write(.env*)');
    expect((result.team.claude as any)?.policies?.permissions?.rules?.deny).toContain('Bash(rm -rf *)');
    expect((result.team.claude as any)?.policies?.sandbox?.enabled).toBe(true);
    expect((result.team.claude as any)?.policies?.sandbox?.auto_allow_bash).toBe(true);
  });

  it('imports hooks from settings.json (camelCase -> snake_case)', () => {
    setupClaudeDir({
      'dev.md': '---\nname: dev\ndescription: Dev\n---\n',
    });
    setupSettings({
      hooks: {
        PreToolUse: [
          { matcher: 'Bash', hooks: [{ type: 'command', command: 'echo pre' }] },
        ],
        PostToolUse: [
          { matcher: 'Write', hooks: [{ type: 'command', command: 'echo post' }] },
        ],
      },
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    expect((result.team.claude as any)?.policies?.hooks?.pre_tool_use).toEqual([
      { matcher: 'Bash', command: 'echo pre' },
    ]);
    expect((result.team.claude as any)?.policies?.hooks?.post_tool_use).toEqual([
      { matcher: 'Write', command: 'echo post' },
    ]);
  });

  it('warns on unknown model ID', () => {
    setupClaudeDir({
      'agent.md': '---\nname: agent\ndescription: Test\nmodel: claude-unknown-99\n---\n',
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    expect(result.warnings.some((w) => w.message.includes('Unknown model'))).toBe(true);
    expect((result.team.claude?.agents.agent as any).model).toBeUndefined();
  });

  it('warns when no agent files found', () => {
    mkdirSync(join(TMP, '.claude', 'agents'), { recursive: true });

    const result = importFromClaudeDir(TMP, 'test-project');
    expect(result.warnings.some((w) => w.message.includes('No agent .md files'))).toBe(true);
  });

  it('strips generated sections (Skills, Delegation, Constraints) from instructions', () => {
    setupClaudeDir({
      'dev.md': [
        '---',
        'name: dev',
        'description: Dev',
        '---',
        '',
        'Write clean code.',
        '',
        '## Skills',
        '',
        'Use the following skills when applicable: lint.',
        '',
        '## Delegation',
        '',
        'You can delegate tasks to the following agents: reviewer.',
        '',
        '## Constraints',
        '',
        '- Maximum turns: 10',
      ].join('\n'),
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    expect((result.team.claude?.agents.dev as any).instruction_blocks).toEqual([{ kind: 'behavior', content: 'Write clean code.' }]);
    expect((result.team.claude?.agents.dev as any).forge?.handoffs).toEqual(['reviewer']);
  });

  it('uses filename as agent name when frontmatter name is missing', () => {
    setupClaudeDir({
      'my-agent.md': '---\ndescription: Agent without name field\n---\n',
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    expect(result.team.claude?.agents['my-agent']).toBeDefined();
  });

  it('sets project name correctly', () => {
    setupClaudeDir({
      'dev.md': '---\nname: dev\ndescription: Dev\n---\n',
    });

    const result = importFromClaudeDir(TMP, 'cool-project');
    expect(result.team.project.name).toBe('cool-project');
    expect(result.team.version).toBe('2');
  });

  it('imports disallowedTools from frontmatter', () => {
    setupClaudeDir({
      'reader.md': '---\nname: reader\ndescription: Reader\ndisallowedTools: [Write, Edit, Bash]\n---\n',
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    expect((result.team.claude?.agents.reader as any).disallowed_tools).toEqual(['Write', 'Edit', 'Bash']);
  });

  it('reverse-maps canonical tools to AgentSkill names when all tools for a skill are present', () => {
    setupClaudeDir({
      'fullstack.md': [
        '---',
        'name: fullstack',
        'description: Full-stack agent',
        'tools: [Read, Grep, Glob, Write, Edit, MultiEdit, Bash, Agent]',
        '---',
      ].join('\n'),
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    const tools = (result.team.claude?.agents.fullstack as any).tools ?? [];
    // All four skills should be present
    expect(tools).toContain('read_files');
    expect(tools).toContain('write_files');
    expect(tools).toContain('execute');
    expect(tools).toContain('delegate');
    // No raw CanonicalTool names should remain
    expect(tools).not.toContain('Read');
    expect(tools).not.toContain('Write');
    expect(tools).not.toContain('Bash');
    expect(tools).not.toContain('Agent');
    expect(result.warnings).toHaveLength(0);
  });

  it('keeps partial tool sets as raw tool names when skill cannot be completed', () => {
    setupClaudeDir({
      'partial.md': [
        '---',
        'name: partial',
        'description: Partial tools agent',
        // read_files requires Read+Grep+Glob; only Read here
        'tools: [Read, Bash]',
        '---',
      ].join('\n'),
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    const tools = (result.team.claude?.agents.partial as any).tools ?? [];
    expect(tools).toContain('execute');
    expect(tools).toContain('Read');
    expect(tools).not.toContain('read_files');
  });

  it('handles CRLF line endings in agent files', () => {
    setupClaudeDir({
      'win-agent.md': '---\r\nname: win-agent\r\ndescription: Windows agent\r\nmodel: opus\r\n---\r\n\r\nWindows instructions.\r\n',
    });

    const result = importFromClaudeDir(TMP, 'test-project');
    expect((result.team.claude?.agents['win-agent'] as any).description).toBe('Windows agent');
    expect((result.team.claude?.agents['win-agent'] as any).model).toBe('opus');
    expect((result.team.claude?.agents['win-agent'] as any).instruction_blocks).toEqual([{ kind: 'behavior', content: 'Windows instructions.' }]);
  });
});

describe('importFromCodexDir', () => {
  beforeEach(() => {
    TMP = mkdtempSync(join(tmpdir(), 'teamcast-codex-import-'));
  });

  afterEach(() => {
    if (existsSync(TMP)) rmSync(TMP, { recursive: true });
  });

  it('imports codex agents from config.toml and per-agent configs', () => {
    setupCodexDir([
      {
        name: 'developer',
        description: 'Builds features',
        content: [
          'model = "gpt-5-codex"',
          'model_reasoning_effort = "high"',
          'sandbox_mode = "workspace-write"',
          'developer_instructions = """',
          'You are developer. Builds features',
          '',
          'Implement the requested changes.',
          '',
          '## Delegation',
          '',
          'You may delegate to: reviewer.',
          '',
          '## Allowed Tool Intents',
          '',
          'read_file, write_file, execute_command, search_codebase',
          '',
          '## Skill Docs',
          '',
          'Follow these local skills when relevant: test-first, clean-code.',
          '"""',
        ].join('\n'),
      },
    ]);

    const result = importFromCodexDir(TMP, 'test-project');
    const agent = result.team.codex?.agents.developer as any;

    expect(agent?.description).toBe('Builds features');
    expect(agent?.model).toBe('gpt-5-codex');
    expect(agent?.reasoning_effort).toBe('high');
    expect(agent?.tools).toEqual(['read_file', 'write_file', 'execute_command', 'search_codebase']);
    expect(agent?.skills).toEqual(['test-first', 'clean-code']);
    expect(agent?.forge?.handoffs).toEqual(['reviewer']);
    expect(agent?.instruction_blocks).toEqual([{ kind: 'behavior', content: 'Implement the requested changes.' }]);
  });

  it('warns when no codex agent files are found', () => {
    mkdirSync(join(TMP, '.codex', 'agents'), { recursive: true });
    writeFileSync(join(TMP, '.codex', 'config.toml'), '[features]\nmulti_agent = true\n', 'utf-8');

    const result = importFromCodexDir(TMP, 'test-project');

    expect(result.warnings.some((warning) => warning.message.includes('No agent .toml files'))).toBe(true);
  });
});
